### ISSUE TITLE
vue config

### ISSUE THREAD

**Issue by dennis2k** [michaelolof/vue-literal-compiler#3]
Hi @michaelolof - great project you got going here - im really excitet about it cause as we all know typescript and vue is not always working well together. 

Im currently working on a project using vue cli 3
do you have an example of the webpack configuration extending the vue.config.js ?

**Comment by michaelolof** [comment]
Hello there.

So a basic `vue.config.js` will look like this
```ts
module.exports = {
  chainWebpack: config => {
    
    config.module.rule("ts").exclude.add(/\.lit\.ts$/);
   
    config.module.rule("lit")
    .test(/\.lit\.ts$/)
      .use("vue-loader")
      .loader("vue-loader")
      .options({
        compiler: require("vue-literal-compiler"),
      })
  }

}
```

**Comment by michaelolof** [comment]
In the future. When I'm less busy. I might write a vue cli 3 plugin for it.

**Comment by dennis2k** [comment]
fantastic - the config worked like a charm! I'm looking forward to trying it out
